### ISSUE TITLE
Inputting very large numbers cause a crash

### ISSUE THREAD

**Issue by Crazys-Corner** [SilentAssassin101/PyCalcGPA#7]
I put 42111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111421111111111111114211111111111111142111111111111111

and it died...

**Comment by SilentAssassin101** [comment]
Fixed in next release
